//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maker.Models
{
    
    public class Customer
    {
        private string Id;
        private string name;
        private string Age;
        public virtual string Id
        {
            get
            {
                return this.Id;
            }
            set
            {
                this.Id = value;
            }
        }
        public virtual string name
        {
            get
            {
                return this.name;
            }
            set
            {
                this.name = value;
            }
        }
        public virtual string Age
        {
            get
            {
                return this.Age;
            }
            set
            {
                this.Age = value;
            }
        }
    }
}
